--- #YAML:1.0
name:               Code-Generator-Perl
version:            0.03
abstract:           Perl module for generating perl modules
author:
    - nazri <nazri@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  2.121
    File::Path:    2.07
    File::Spec:    3.29
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
